version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    image: backend:latest
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/postgres
    depends_on:
      - postgres
    ports:
      - "3001:3001"

volumes:
  db:
